import { Rosarivo } from "next/font/google";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Header from "@/_components/header";
import Footer from "@/_components/footer";
import { AnimationProvider } from "@/_contexts/AnimationContext";

const rosarivo = Rosarivo({
  variable: "--font-rosarivo",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Artheca",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="fr"
      className={`${rosarivo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NuqsAdapter>
          <AnimationProvider>
            <Header />
            {children}
            <Footer />
          </AnimationProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
